### ISSUE TITLE
Propose a way to use a different DEM per lizmap project

### ISSUE THREAD

**Issue by mdouchin** [arno974/lizmap-altiProfil#1]
What about a way to declare, for each published QGIS project, a different PostgreSQL rater table to use ?

This would allow users with many maps in different areas to use the correct precise DEM for the map.

Possible options

* add a configuration as a JSON file, alongside the QGIS project. myproject.qgs.altiprofil with no sensitive credentials, but the schema and table of the dem. The sensitive credentials will remain in the `localconfig.ini.php`
* add the altiprofil module in Lizmap sources, and add a new tab in lizmap QGIS plugin to configure.

**Comment by mdouchin** [comment]
I will propose a pull request for this issue

**Comment by arno974** [comment]
Really Good Idea! Let me know if I can help you.

**Comment by mdouchin** [comment]
Also done and proposed via #3 !
