### ISSUE TITLE
Erreur st_makepoint

### ISSUE THREAD

**Issue by relaire** [arno974/lizmap-altiProfil#12]
Bonjour,
Je tente d'Integer le module altiProfil sur mon instance lizmap (3.5) en utilisant mon propre DEM sur un serveur PostgreSQL diffèrent du lizmap.
La connexion au raster se fait bien, mais je n'arrive pas à obtenir le profil et je retrouve systématiquement cette erreur dans les logs de lizmap :
`Erreur dans la requête (ERREUR:  la fonction st_makepoint(numeric, numeric) n'existe pas
LINE 4:                 ST_Transform(ST_SetSRID(ST_MakePoint(3.55783...
HINT:  Aucune fonction ne correspond au nom donné et aux types d'arguments.
Vous devez ajouter des conversions explicites de type.(
            SELECT ST_Value(
                bdalti_rge5.rast,
                ST_Transform(ST_SetSRID(ST_MakePoint(3.557834, 45.790632),4326),2154)
            ) as z
            FROM bdalti_rge5
            WHERE ST_Intersects(
                bdalti_rge5.rast,
                ST_Transform(ST_SetSRID(ST_MakePoint(3.557834, 45.790632),4326),2154)`

Ce que je ne comprends pas bien, car la requête semble fonctionnelle. Et elle fonctionne directement en console sur le serveur Postgres.

J'ai bien tenter de contraindre en ajoutant des `::float` directement sans _altiprofil.ini.php_ sans succès.
Une idée ?
Merci
Renaud

**Comment by arno974** [comment]
@relaire cela semble effectivement une erreur de configuration de base de données.
Vérifiez bien que vous vous connectez à la bonne base. Comme suggéré par @Gustry est-ce que vous avez ajouté un paramètre search_path à la connexion ? Si c'est le cas, l'application ne pourra "chercher" que dans le schéma précisé. Or, les fonctions PostGIS se trouvent habituellement dans "public".

**Comment by relaire** [comment]
J'ai bien précisé le search_path dans le profiles.ini.php, j'ai même tenté de déplacer les tables dans le schéma public, avec le meme résultat ...

**Comment by arno974** [comment]
Malheureusement, le module lui-même ne semble pas être en cause. Je ne pourrais pas beaucoup vous aider. Au regard de l'erreur, il s'agit probablement d'une mauvaise configuration. La requête se fait bien, mais l'interaction avec la base de données semble poser problème. Le plus problème semble être une erreur dans la configuration de `[jdb:altiProfil]` dans `profiles.ini.php`.

**Comment by relaire** [comment]
Ok, merci du retour
