### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by NyakudyaA** [arno974/lizmap-altiProfil#13]
Following the instructions, I get the following error
![install-error](https://user-images.githubusercontent.com/2510900/157863875-741e6c78-3c8c-435d-9904-9441ca42751a.png)

However manual installation works

**NB** Running in docker using the lizmap-docker-compose without any modifications and sample projects

**Comment by Gustry** [comment]
For curiosity, where did you read `lizmap/` ?
The name of the repository on packagist is `arno974/lizmap-altiprofil`
CF https://packagist.org/packages/arno974/lizmap-altiprofil

You should change the name, it should work.

**Comment by Gustry** [comment]
Ok, I saw it in the readme. I will update wiht a PR
