### ISSUE TITLE
Package conflict name during composer install

### ISSUE THREAD

**Issue by NyakudyaA** [arno974/lizmap-altiProfil#17]
# Problem
Using https://github.com/arno974/lizmap-altiProfil/blob/master/composer.json to install with compose you encounter the error

![composer](https://user-images.githubusercontent.com/2510900/162754934-4c804262-3c98-45f6-b33b-a2cd6cdb8015.png)

**Comment by Gustry** [comment]
I think you shouldn't use this file https://github.com/arno974/lizmap-altiProfil/blob/master/composer.json. This is the composer file describing the `altiprofil` package, so your error is expected. Why are you using this composer file ?

I guess you wanted to use https://github.com/3liz/lizmap-web-client/blob/master/lizmap/my-packages/composer.json.dist this one instead.
Running the command `composer require` will edit this file to add an external package into the dependencies.

**Comment by Gustry** [comment]
@NyakudyaA Is this issue still relevant, or can we close ?

**Comment by NyakudyaA** [comment]
All sorted @Gustry , thanks
