### ISSUE TITLE
0.5.3: Selected position in the profile is not shown in the site plan

### ISSUE THREAD

**Issue by guenterw** [arno974/lizmap-altiProfil#46]
If a certain position is marked in the profile, this position was previously also displayed in the site plan. It is currently not displayed in 0.5.3.

Lizmap 3.8.2 mit altiProfil 0.5.3 (https://cx21-8.webgis.biz/)
![image](https://github.com/user-attachments/assets/5ff5c4e5-3dc4-42cd-8d40-c41eba736e0d)

Lizmap 3.7.11-pre (https://cx21-7.webgis.biz/)
![image](https://github.com/user-attachments/assets/bfc5d7f4-4363-4906-a818-8f6404b5c8b6)

**Comment by nworr** [comment]
#49 fix the bug,  i'm waiting for the next release to close the issue

**Comment by nworr** [comment]
fixed and released https://github.com/arno974/lizmap-altiProfil/releases/tag/0.5.4
/close

**Comment by guenterw** [comment]
@nworr, Thank you very much!
Version 0.5.5 now works as usual in V3.8, V3.9-pre and also in V3.10-pre  
https://cx21-8.webgis.biz/index.php/view/map?repository=zaltiprofil&project=test_profil_3_34
https://cx21-9.webgis.biz/index.php/view/map?repository=zaltiprofil&project=test_profil_3_34
https://cx21-10.webgis.biz/index.php/view/map?repository=zaltiprofil&project=test_profil_3_34
