### ISSUE TITLE
0.5.3 with Lizmap 3.9.0-pre: No profile window with Dock panel Right-dock

### ISSUE THREAD

**Issue by guenterw** [arno974/lizmap-altiProfil#48]
In version 0.5.3 with Lizmap 3.9.0-pre (01.10.2024), no profile window opens if the dock panel is set to right-dock.
With Dock panel Dock or Mini-dock it works the same as under Lizmap 3.8.2, see https://github.com/arno974/lizmap-altiProfil/issues/46
Example: https://cx21-9.webgis.biz

**Comment by guenterw** [comment]
sorry, I have no idea what the “Bootstrap5 migration” is

**Comment by Gustry** [comment]
No problem.
That's why my colleague was quoted ;-)

**Comment by nboisteault** [comment]
The problem is not linked to altiProfil. I made a [fix](1ff17460ccd2900b3745516f8e50bfef23f7d9ba).
@guenterw Please update Lizmap and tell us if it fixes the problem.

**Comment by guenterw** [comment]
yes, with the current 3.9.0-pre it also works with the right-dock. 
See the example above, now with the 3.9.0-pre from 09.10.

**Comment by Gustry** [comment]
Link on GitHub : https://github.com/3liz/lizmap-web-client/commit/1ff17460ccd2900b3745516f8e50bfef23f7d9ba
